- src/components/form/components/__test__/__snapshots__/checkbox.test.js.snap
- src/components/form/components/__test__/__snapshots__/input.test.js.snap
- src/components/form/components/__test__/__snapshots__/select.test.js.snap
- src/components/form/components/__test__/__snapshots__/textarea.test.js.snap
- src/components/form/components/checkbox.js
- src/components/form/components/input.js
- src/components/form/components/radio.js
- src/components/form/components/select.js
- src/components/form/components/textarea.js
- src/components/form/form.story.js
Add name to Form elements to allow https://reactjs.org/docs/forms.html#handling-multiple-inputs (This will resolve issue #4
> Add name to form elements

- src/__test__/__snapshots__/index.test.js.snap
- src/index.js
Hi, I don't know if Card is ready for production yet, if it is, would you check out this small PR ? Card isn't exported from the main index.js and thus not usable.
Is it okay if I sometimes come with these requests and little helps?
> Export Card component in index.js

- src/components/form/components/input.js
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search
> support for search HTML5 input type

- package.json
- yarn.lock
> nodemon updated to 1.17.5

- src/components/icon/icon.story.js
> Icon doc update

- src/components/form/components/input.js
small change, was missing from the previous number support PR
> Modified input component props to suport the number type

- src/components/form/components/input.js
> Add color, date propTypes to input

- README.md
In reference to discussion on #74 -- GatsbyJS v2 doc additions
> added Gatsby.js v2 webpack info to README.md

- index.d.ts
- src/components/hero/hero.js
> [Types] Fix incorrect size.

- index.d.ts
> fixed fullwidth casing on table size prop

- package-lock.json
- src/components/dropdown/__test__/__snapshots__/dropdown.test.js.snap
- src/components/dropdown/__test__/dropdown.test.js
- src/components/dropdown/dropdown.js
- src/components/dropdown/dropdown.story.js
Doc: https://bulma.io/documentation/components/dropdown/  
`label: PropTypes.string`  
Default value: `undefined`  
- If a label is passed, it will be shown;
- if not, the label of the first dropdown item will be shown;
- **(Edit:)** If a value is defined, the label of the dropdown item with that value will be shown.
- The custom label will be replaced with the label of the clicked dropdown item, no matter whether a label is passed.
> Custom label in <Dropdown />

- README.md
Found some typos in the readme.md
Thanks!
> fix typos in README file

- src/components/form/__test__/__snapshots__/file-input.test.js.snap
- src/components/form/__test__/file-input.test.js
- src/components/form/components/input-file.js
> Fix #180 Add input file attributes to InputFile

- README.md
This clarifies the readme to avoid losing an afternoon scratching one's head as to the cause of #185
> Update README to avoid #185

- index.d.ts
https://github.com/couds/react-bulma-components/blob/master/src/components/dropdown/dropdown.js#L32
> Fix missing label type to DropdownModifierProps

- index.d.ts
from src/components/form/components/input-file.js:134
> Add missing type definitions for InputFile

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/button/button.story.js
- src/components/image/__test__/__snapshots__/image.test.js.snap
- src/components/image/__test__/image.test.js
- src/components/image/image.js
- src/components/image/image.story.js
- src/components/navbar/navbar.story.js
- src/components/panel/__test__/__snapshots__/panel.test.js.snap
- src/components/panel/__test__/panel.test.js
- src/components/panel/panel.js
- src/components/panel/panel.story.js
- src/constants.js
- src/modifiers/colors.js
Closes #237  
Changes:
- `<Panel />` component now has a `color` prop that accepts the same value as other components that support color like `<Button />`
- New `colorVariant` modifier that accepts two values: `light` and `dark`. Equivalent to Bulma's `is-light` and `is-dark` modifiers.
- Added a changelog.
> Update to Bulma v0.8.2

- README.md
> Update Next.js installation instructions

- src/components/panel/panel.js
> Fix <Panel /> incorrect prop: color instead of colors

- README.md
I found this information in a closed ticket. This wasn't obvious to someone who is not very experienced in React, so hopefully will help others.
> Updated docs for form elements

- src/components/tag/tag.story.js
> fix for storybook warning color

- src/components/navbar/navbar.story.js
Fix typo in Navbar Component storybook file. 😁
> Fix little typo in navbar component storybook

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/help.md
@couds i thought it'd be a good idea to have issue templates to help organize issues a bit.
> Add issue templates

- src/components/pagination/__test__/__snapshots__/pagination.test.js.snap
- src/components/pagination/__test__/pagination.test.js
- src/components/pagination/index.d.ts
- src/components/pagination/pagination.js
- src/components/pagination/pagination.story.js
I am looking for adding first and last page in the pagination component and i found the following pull request.
https://github.com/couds/react-bulma-components/pull/100
The code works great so i forked the latest master and open this new pull request.
Thanks @haflinger and all the authors who have been working on this great module.
> Add pagination first last pages

- documentation/docs/components/components/pagination.md
As suggested in https://github.com/couds/react-bulma-components/pull/283.
> Add pagination first last pages (documentation)

- src/components/form/components/__test__/__snapshots__/select.test.js.snap
- src/components/form/components/__test__/select.test.js
- src/components/form/components/select.js
> Fix Warning: Failed prop type: Invalid prop value supplied to Select

- README.md
peedr dependency -> peer dependency.
Is this a typo?🤔
> Is this a typo?🤔

- src/components/index.d.ts
- src/components/modal/index.d.ts
> Fixes issues with modal children (#302)

- src/components/dropdown/index.d.ts
Just came across this, much clearer once it is in the type definition
> add icon to dropdown props definition

- src/components/dropdown/index.d.ts
- src/components/modal/modal.story.mdx
the dropdown disabled prop is required, but has a default value.   I've made it optional, like the button  disabled prop
> Make dropdown disabled prop optional

- package-lock.json
- src/components/dropdown/__test__/dropdown.test.js
- src/components/dropdown/dropdown.js
- src/components/dropdown/index.d.ts
Added a new `menuId` prop to `<Dropdown>`. `Dropdown` will pass the ID to the underlying `<div class="dropdown-menu">`. This allows users to access the menu through the ID. By default, the ID is `"dropdown-menu"`.
Closes #373 
Cc @couds @smeknamn
> Add menuId prop to allow passing of ID to dropdown menu

- src/components/form/index.d.ts
- src/components/navbar/index.d.ts
fix https://github.com/couds/react-bulma-components/issues/402 
fix https://github.com/couds/react-bulma-components/issues/399
> fix: add typings for form.input & navbar.item
