couds/react-bulma-components

src/components/navbar/navbar.js

When importer navbar as a single component in another project that throw an error because services is not defined as a root resolver.
Solution: Use relative imports

Use relative import on navbar for service

---

src/components/heading/heading.story.js

Seems like a documentation fix to show `renderAs` for the heading...
Fixes #18

Add renderAs=h2 to Heading storybook

---

src/components/media/media.story.js

remove unnecesary renderAs on Image Element in Media storybook

---

src/components/form/components/input.js

the number input should be supported as it queues mobile devices to present a number keyboard when its specified.
Bulma supports this type of input (which ends up being just a specialized text input)

Support for HTML5 number input

---

src/components/button/button.js
src/components/button/button.story.js

fix for #52 
@couds i just realised that prettier changed the styling a bit. Is it a problem for you?

rounded prop added

---

README.md

Based on issue #74, I've adjusted the Readme to include:
* Additional info on the Gatsby setup
* Making it clearer you may need to make a `_variables.sass` file even if you don't want to override styles
* Made it clearer that the path needs to end in _variables.sass - that was ambiguous when I was trying to use this

Readme: Include Gatsby webpack incantation

---

src/components/form/components/input.js

I was trying to use the time input like described [here (on MDN)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time) but it gave me errors.

add `time` as possible type for Input

---

src/components/form/components/__test__/__snapshots__/checkbox.test.js.snap
src/components/form/components/__test__/checkbox.test.js
src/components/form/components/checkbox.js

Problem:
The Checkbox component lists `checked` as a `prop`, but it doesn't actually set the `checked` attribute of its `<input>`. 
Solution:
This PR propagates the checked state to the input.

Fix Checkbox component to propagate checked state

---

package-lock.json
src/components/dropdown/__test__/__snapshots__/dropdown.test.js.snap
src/components/dropdown/__test__/dropdown.test.js
src/components/dropdown/dropdown.js
src/components/dropdown/dropdown.story.js

Doc for `is-up` modifier for `dropdown`: https://bulma.io/documentation/components/dropdown/#dropup  
`align` prop is replaced by `right` and `up` props because `is-right` and `is-up` modifiers can co-exist, but `align` only accepts `'right'` as the value; they are also more descriptive and are more aligned to the official documentation.  
Related issue: #107

Added support for 'is-up' in <Dropdown />, closes #107

---

README.md

"Advanced Setup" link in README.md is invalid.
So, I fixed this url.

Fix Advanced Setup URL

---

src/components/card/card.story.js
src/components/media/media.story.js
src/components/modal/modal.story.js

This fixes in particular 
https://github.com/couds/react-bulma-components/issues/144

fixed examples with Image not to have unsupported renderAs prop

---

public/package-lock.json
public/package.json

Adding cross-env make npm scripts work on all platform.
For example, NODE_PATH wasn't working on my OS (Windows).
Related error (error is in french, but basically it says that NODE_PATH is not recognized) :
```bash
$ npm start
> public@0.1.0 start C:\Users\Jeremy\www\react-bulma-components\public
> NODE_PATH=./src react-scripts start
'NODE_PATH' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! public@0.1.0 start: `NODE_PATH=./src react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the public@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found …
```

feat: add cross-env to devDependencies and in npm scripts

---

src/components/pagination/__test__/__snapshots__/pagination.test.js.snap
src/components/pagination/__test__/pagination.test.js
src/components/pagination/pagination.js
src/components/pagination/pagination.story.js

A prop `disabled: PropTypes.bool` is added to `<Pagination />` which disables all buttons in pagination.
Closes #150.

Can now manually disable prev/next button in Pagination component

---

src/components/menu/__test__/__snapshots__/menu.test.js.snap
src/components/menu/components/list/components/item.js
src/components/menu/menu.story.js

Content inside `list-item` must be wrapped with an `<a>` anchor or the list item will not be styled correctly.  
Closes #169

List items containing custom children will now be styled correctly

---

package.json

Peer dependencies for react and react-dom were fixed to version 16.3.0. Made that into a minimal requirement.
Fixes #191

Fixed react and react-dom peer dependencies

---

src/components/utils.sass

The SASS `!default` syntax expects the "override" to be defined before the fallback. Thus `_variables.scss` should come first.
The new ordering will allow to, for example, define a different value for `$gap`, which will be taken into account in `~bulma/sass/utilities/initial-variables.sass` in calculating value for `$desktop`.
In the current ordering if i want to change the value for `$gap` i have to also modify values for all other variables where value of `$gap` is used.

Change order of imports in utils.scss

---

src/components/columns/columns.js
src/components/columns/columns.story.js

[Docs for is-vcentered](https://bulma.io/documentation/columns/options/#vertical-alignment)
New prop for `Columns`: `vCentered: PropTypes.bool`
Closes #194

Added vertical alignment support for Columns

---

src/components/form/components/input.js

The input value proptype is set to `string` so passing a number into to it, will show `Failed prop type: Invalid prop value of type number supplied to Input, expected string`. This commit extends the value prop to accept both numbers and strings. 
```js
<Input
type="number"
placeholder="Text input"
value={1}
/>
```

extend input value PropType to accept numbers

---

src/components/modal/modal.js

IE11 does not support the remove method on HTML elements. This PR implements a recommended way around it.

fix: remove method on html element this.portalElement

---

README.md

Includes example on how to use the `domRef` prop.
Closes #208

Documented domRef prop in README.md

---

src/components/pagination/pagination.js

Currently, the code `<Pagination current={current} total={5} delta={2} />` produces varied-size paginations depending on the `current` page, e.g.
* `current=1` => [1, 2, 3, 4, 5]
* `current=2` => [1, 2, 3, 4]
* `current=3` => [1, 2, 3, 4, 5]
* `current=4` => [2, 3, 4, 5]
* `current=5` => [1, 2, 3, 4, 5]
I would expect the pagination to stay the same size ([1, 2, 3, 4, 5], i.e. `min(total, 2 * delta + 1)`) regardless of `current` changes, so this PR does that. 
Btw, I wasn't sure if the library is allowed to use Math.max and Math.min, so the PR uses simple comparison instead!
Full CRA code to reproduce the behaviour:
```
import React, { useState } from 'react';
import Pagination from './react-bulma-components/src/components/pagination';
import './App.scss';
function App() {
const [current, …
```

Make pagination to be fixed-length

---

src/components/level/__test__/__snapshots__/level.test.js.snap
src/components/level/__test__/level.test.js
src/components/level/level.js
src/components/level/level.story.js

I realized `<Level />` was missing `is-mobile` support when making documentation of it.  
**Added prop:**
```
mobile: PropTypes.bool
```
Defaults to `false`.  
[Documentation here.](https://bulma.io/documentation/layout/level/#mobile-level)

Added mobile prop for <Level> component

---

index.d.ts

In trying to add a Progress component to my app, I realized the typing currently does not allow for [Indeterminate Progress Bars](https://bulma.io/documentation/elements/progress/#indeterminate) as they can only be triggered when `value` is not added, and it's not an optional property.
This fixes that to conform with docs and allow indeterminate loaders.

fix: Progress value should be optional

---

README.md

Replaced code in next.js documentation from `next-plugin-transpile-modules` to `next-transpile-modules`

README.md Next.js correction

---

src/components/table/components/container.js
src/components/table/table.js
src/components/table/table.story.js

This adds a missing element `Table.Container` as described in Bulma documentation [here](https://bulma.io/documentation/elements/table/#table-container).
This can be used to create a scrollable table - I needed to use this in my app and realized it had not been added here :)
cc @MrCreeper1008

fix: add missing Table.Container element

---

src/components/table/table.js

This PR fixes a missing Table modifier for hoverability:
I wasn't sure whether to also add a new storybook example (there don't seem to be many for Table modifiers) but can if needed!
cc @MrCreeper1008

fix: add missing table hoverable prop

---

src/components/columns/index.d.ts

Adds string-style column widths to types to avoid type errors on legitimate widths.

Add string column widths to types

---

src/components/index.d.ts

Uses ElementType (https://flow.org/en/docs/react/types/#toc-react-elementtype) to fix #314

Fix issue with RenderAsComponent type

---

src/components/progress/index.d.ts

Allows creating Indeterminate [progress bars](https://bulma.io/documentation/elements/progress/#indeterminate).

Make value and max props optional in Progress component

---

src/components/form/components/checkbox.js

Currently, the `checked` property is not applied.

Add 'checked' property to the checkbox

---

src/components/icon/__test__/__snapshots__/icon.test.js.snap
src/components/icon/__test__/icon.test.js
src/components/icon/icon.js

Currently if `Icon` `text` prop is enabled, both `icon` and `icon-text` classes are added, causing layout issue. From Bulma's documentation, only the `icon-text` class is required. This PR addresses this issue.
Closes #335, cc @Tstassin

add only icon-text class when Icon text prop is enabled

---

src/components/icon/__test__/__snapshots__/icon.test.js.snap
src/components/icon/__test__/icon.test.js
src/components/icon/components/text/index.js
src/components/icon/components/text/text.js
src/components/icon/icon.js
src/components/icon/icon.story.js
src/components/icon/icon.story.mdx
src/components/icon/index.d.ts

Move Icon.Text as his own component as suggested on Discussion #338

Add Icon.Text and TS definition

---

src/components/index.d.ts

The domRef definition that was there would have a nonsensical type like `React.RefObject<"input">` when it should be referring to the actual element like `React.RefObject<HTMLInputElement>` based on `TComponent`. This would necessitate doing ugly casts like
```
ref as unknown as HTMLInputElement
```

fix: domRef in ElementProps was missing React.ElementRef

---

src/components/pagination/pagination.js

I think the title here is misleading, as the previous button is not always the first page. 
Also, the text is not customizable as the Nest/Previous button.

Remove misleading title on previous button in Pagination

---

src/components/columns/columns.js
src/components/columns/index.d.ts

The type did not match what the component was expecting. Adds `GapSize` type and uses it in `GapProps.gap` + `Columns.gap`.

🐞 fix: update type for gap property on columns to take a number
